/** @type {import('stylelint').Config} */
export default {
  customSyntax: 'postcss-styled-syntax',
  extends: ['stylelint-config-recommended'],
  plugins: ['stylelint-order'],

  rules: {
    // Disable rules that conflict with styled-components
    'nesting-selector-no-missing-scoping-root': null,

    // At-rule handling
    'at-rule-no-unknown': [true, { ignoreAtRules: ['extends', 'apply'] }],

    // Font rules
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'font-weight-notation': 'named-where-possible',
    'font-family-name-quotes': 'always-unless-keyword',

    // Function rules
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,

    // Keyframe rules
    'keyframe-declaration-no-important': true,

    // Media rules
    'media-feature-name-no-unknown': true,

    // General rules
    'no-descending-specificity': null,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': null,
    'no-empty-source': null,
    'no-invalid-double-slash-comments': true,
    'block-no-empty': null,

    // Property rules
    'property-no-unknown': true,
    'property-no-vendor-prefix': [true, { ignoreProperties: ['mask-composite'] }],
    'shorthand-property-no-redundant-values': true,

    // Selector rules
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': [true, { ignore: ['custom-elements'] }],
    'selector-no-vendor-prefix': true,
    'selector-no-qualifying-type': [true, { ignore: ['attribute', 'class'] }],
    'selector-max-id': 0,
    'selector-max-universal': 1,
    'selector-max-type': 3,
    'selector-max-class': 4,
    'selector-max-attribute': 2,
    'selector-max-pseudo-class': 3,
    'selector-max-combinators': 3,
    'selector-max-compound-selectors': 4,

    // String rules
    'string-no-newline': true,

    // Color rules
    'color-no-invalid-hex': true,
    'color-named': 'never',
    'color-hex-length': 'long',
    'color-function-notation': 'modern',

    // Value rules
    'value-no-vendor-prefix': [true, { ignoreValues: ['xor'] }],
    'value-keyword-case': null,

    // Number and unit rules
    'number-max-precision': 3,
    'length-zero-no-unit': true,
    'unit-allowed-list': ['px', '%', 's', 'ms', 'fr', 'rem', 'em', 'vw', 'vh', 'vmin', 'vmax', 'deg', 'turn', 'rad'],
    'unit-no-unknown': [true, { ignoreUnits: ['/px`/'] }],

    // Declaration rules
    'declaration-property-value-no-unknown': [true, { ignoreProperties: { 'mask-composite': ['xor'] } }],
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-no-important': [true, { severity: 'warning' }],
    'declaration-empty-line-before': null,

    // Other rules
    'rule-empty-line-before': null,
    'max-nesting-depth': null,
    'media-feature-name-no-vendor-prefix': true,
    'at-rule-no-vendor-prefix': true,

    // Pattern rules
    'custom-property-pattern': '^([a-z][a-z0-9]*)(-[a-z0-9]+)*$',
    'selector-class-pattern': null,
    'selector-id-pattern': null,

    // Property order (following your existing order)
    'order/properties-order': [
      [
        'content',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'flex',
        'flex-direction',
        'flex-wrap',
        'justify-content',
        'align-items',
        'align-content',
        'gap',
        'grid',
        'grid-template',
        'grid-template-rows',
        'grid-template-columns',
        'grid-area',
        'float',
        'clear',
        'box-sizing',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'border',
        'border-spacing',
        'border-collapse',
        'border-width',
        'border-style',
        'border-color',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        'border-radius',
        'outline',
        'outline-width',
        'outline-style',
        'outline-color',
        'outline-offset',
        'background',
        'background-color',
        'background-image',
        'background-repeat',
        'background-attachment',
        'background-position',
        'background-size',
        'background-clip',
        'background-origin',
        'box-shadow',
        'opacity',
        'filter',
        'list-style',
        'list-style-position',
        'list-style-type',
        'list-style-image',
        'table-layout',
        'empty-cells',
        'caption-side',
        'font',
        'font-weight',
        'font-size',
        'line-height',
        'font-family',
        'vertical-align',
        'text-align',
        'direction',
        'color',
        'text-decoration',
        'text-shadow',
        'text-transform',
        'text-indent',
        'text-overflow',
        'letter-spacing',
        'word-spacing',
        'white-space',
        'word-break',
        'word-wrap',
        'hyphens',
        'cursor',
        'pointer-events',
        'user-select',
        'appearance',
        'overflow',
        'overflow-x',
        'overflow-y',
        'overflow-scrolling',
        'transform',
        'transform-origin',
        'transform-style',
        'perspective',
        'perspective-origin',
        'backface-visibility',
        'transition',
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-play-state',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
      ],
      { unspecified: 'bottomAlphabetical' },
    ],
  },

  ignoreFiles: [
    '**/*.js',
    '**/*.jsx',
    '**/*.md',
    'node_modules/**/*',
    '.next/**/*',
    'build/**/*',
    'dist/**/*',
    '**/gantt/DateBar/styles.ts',
  ],
}
